# Change these first
owner: tenshi-mykiel # Your GitHub organization or username, where this repository lives
repo: tenshi-status # The name of this repository
user-agent: tenshi-mykiel

sites:
  - name: Lima
    url: $LIMA
#  - name: Sierra
#    url: $SIERRA


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /tenshi-status
  logoUrl: https://raw.githubusercontent.com/tenshi-mykiel/tenshi-status/refs/heads/master/favicon.ico
  facivon: https://raw.githubusercontent.com/tenshi-mykiel/tenshi-status/refs/heads/master/favicon.ico
  robotsText: "User-agent: * \n Disallow: /"
  name: Tenshi Status
  introTitle: "Tenshi Status"
  introMessage: How dead are the systems?
  navbar:
    - title: Status
      href: /tenshi-status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
